### ISSUE TITLE
Código fonte do servidor/api e outros

### ISSUE THREAD

**Issue by matheusfelipeog** [RioHackerMakerSpace/rhmsnews.github.io#1]
Olá @rlaneth ;)

Encontrei apenas o front-end open source, que tem o seguinte comportamento:

- Capta o dado informado pelo usuário;
- Faz algumas validações básicas client-side do dado informado;
- Envia o dado para uma api remota (`https://api.radialle.com/api/LeakQuery`) em texto puro.
Exemplo: `https://api.radialle.com/api/LeakQuery?cpf=11111111111` e
- O retorno é tratado no front-end para infomar o usuário.

Já que a informação é passada em texto puro, como isso é tratado pela api? Nota que é necessário o código fonte do servidor para tal análise?

Então, por que o código fonte da api não é aberto (como disse, não encontrei), assim como o front-end, para possíveis análises?

---

PS: Coloque o link desse repositório no rodapé da página, para facilitar que seja encontrado. Foi uma voltinha para encontra-lo haha

**Comment by rlaneth** [comment]
@matheusfelipeog boa noite!

A API é código serverless, uma [Azure Function](https://azure.microsoft.com/en-us/blog/introducing-azure-functions/). Tudo o que ela faz é consultar o [Azure Table storage](https://azure.microsoft.com/en-us/services/storage/tables/), que usamos como banco de dados, e retornar os resultados.

Não publiquei esse código anteriormente pois julguei não ser relevante. É uma função simples, o código não é particularmente bonito ou engenhoso, e a divulgação pouco ajuda a determinar se o site é confiável ou não, uma vez que é impossível para o público garantir que o código que está servindo como _backend_ é realmente o mesmo que foi publicado.

Mas não tenho problemas em mostrá-lo (exceto por um certo constrangimento devido ao fato dele ter não ter sido funcional e esteticamente otimizado). Segue:
https://pastebin.com/gJcEsMyW

Permaneço à disposição para esclarecer quaisquer eventuais dúvidas.

Abraços.

**EDIT**

Somente um adendo: não, o particionamento do banco pelos três primeiros dígitos do CPF não é perfeito. Enquanto o aplicativo estava sendo desenvolvido, o @theldus ajudou demais com esse gráfico de distribuição dos CPFs vazados pelos três primeiros dígitos. Acabei seguindo dessa maneira por falta de uma proposição melhor.

![distribuicao-cpf](https://user-images.githubusercontent.com/10890823/107101330-b9fdd280-67f5-11eb-8480-11697142eb81.png)

**Comment by matheusfelipeog** [comment]
Muito bem, @rlaneth, entendi o funcionamento. Obrigado pelo esclarecimento 😄

**Comment by fakasab790** [comment]
Working site: https://fakasab790.github.io/
